### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by SebChw** [SebChw/Actually-Robust-Training#11]
Stuff to do to get started:
- [ ] [Theory of Audio for ML](https://www.youtube.com/watch?v=iCwMQJnKk2c&list=PL-wATfeyAMNqIee7cH3q1bh4QJFAaeNv0). Most important topics from the series are: 
    * Sound and Waveforms
    * Understanding Audio Signals
    * Types of Audio Features
    * How to Extract Audio Features
    * Short Time Furier Transform
    * Mel Spectrograms Explained Easily
- [ ] [PyTorch](https://www.youtube.com/watch?v=gp2wZqDoJ1Y&list=PL-wATfeyAMNoirN4idjev6aRu8ISZYVWm), in this case especially for Audio classification. This should give you introduction to PyTorch that is necessary
- [ ] [Lightning](https://www.youtube.com/watch?v=Hgg8Xy6IRig) - After doing 2 previous this should be enough
- [ ] [datasets](https://huggingface.co/docs/datasets/audio_load) documentation is really easy to read so no YT needed

**Comment by kordc** [comment]
1st ✅

**Comment by kordc** [comment]
2-4 ✅

**Comment by maciejbilinski** [comment]
Theory of Audio for ML ✅

PyTorch ✅

Lightning ✅

Datasets ✅

**Comment by dkoterwa** [comment]
1-2 ✅

**Comment by dkoterwa** [comment]
3-4 done

**Comment by PaulCodingPractices** [comment]
1 - 2 ✅

**Comment by PaulCodingPractices** [comment]
4✅
