### ISSUE TITLE
Refactor naming of steps

### ISSUE THREAD

**Issue by SebChw** [SebChw/Actually-Robust-Training#140]
Currently we have 4 different functions that manage step names:
* get_name_with_id
* get_full_step_name
* get_model_name
* get_step_id - In one subclass it returns just self.idx in other full identificator.

moreover JSONStepSaver also kind of creates it's own name based on parameters given from the step.

In the ArtProject.fill_step_states we also have nested namings which is weird 

when we check `model_changed` in ArtProject we use get_full_step_name.

Last thing is to move this `step_id` into json file and don't have it in folder name.

Acceptance Criteria:
* Single function that has flags with granurality level - `get_step_name(with_model, with_name, with_id)` so that one doesn't have to wonder what is going on.

**Comment by kordc** [comment]
Done
