### ISSUE TITLE
Use the available Conformer repository and evaluate it on chosen datasets

### ISSUE THREAD

**Issue by kordc** [SebChw/Actually-Robust-Training#15]
- [x] Evaluate Conformer-CTC small and medium on [ASR dataset](https://huggingface.co/datasets/librispeech_asr). Measure the WER and time required for each prediction. Think/read about a time metric, like inference_time/1s_of_sample.
- [ ] Evaluate Conformer-CTC small and medium using the same method on the Snips-SmartSpeaker dataset, which will be available from HF datasets as soon as #37 is closed
- [ ] Add some white, and real-world noise to both datasets above and measure performance on them once again
- [ ] Create a nice-looking comparison, that everyone can look at. 

Use the Nemo ASR collection from Nvidia. I'll post an example in a comment.
https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/api.html

**Comment by kordc** [comment]
I will try to load pre-trained models from https://gitlab.com/Jaco-Assistant/Scribosermo#charbased  
Both char and sentence based

**Comment by kordc** [comment]
+https://github.com/openspeech-team/openspeech

**Comment by kordc** [comment]
Eventually, I used nVidia NEMO - https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_conformer_ctc_small 

For now, I just tested a small CTC conformer on the clean librispeech dataset test dir with a WER of 0.0371.


@SebChw where could I put a notebook in this repository to make everyone see the results and very simple pipeline?

**Comment by kordc** [comment]
Final scores:
Model                        \     WER           \    Inference time
Small Conformer-CTC:      WER 0.0371,    4.79it/s
Medium Conformer-CTC: WER 0.0265,    4.00it/s
Large Conformer-CTC:      WER 0.0219,    1.65it/s

Results from the test-clean set from LibriSpeech. This is enough to say, that the Large model won't make any sense on the edge, so about Conformer, we may stick with the CTC version small or medium. For now, the medium seems to be a better option.

**Comment by SebChw** [comment]
@kordc about the notebook I just shared link to the colab in my issue. We can also discuss it. Maybe put these things on the wiki page? I prefer links to collab than raw notebooks for very small pipelines. Main reason is that one doesn't have to install any additional dependencies locally and doesn't have conflicts

**Comment by SebChw** [comment]
Test it on noisy data, measure real time performance, check how much memory it occupies.

**Comment by kordc** [comment]
@lucapl see the updated description, and this comment on the Nemo use https://github.com/SebChw/audio-research-toolkit/issues/16#issuecomment-1491003499

**Comment by lucapl** [comment]
Measurements for the LibriSpeech dataset
<html>
<body>


Model Size | WER | Items/s | Memory usage [MB]| Total time [s] | Data State
-- | -- | -- | -- | -- | --
small | 0.343465 | 0.769231 | 441.29 | 853.0 | white noise
medium | 0.279747 | 0.591716 | 628.60 | 1106.0 | white noise
large | 0.268031 | 0.246305 | 1249.37 | 2661.0 | white noise
small | 0.037051 | 0.769231 | 768.09 | 855.0 | clean
medium | 0.026400 | 0.526316 | 629.19 | 1248.0 | clean
large | 0.021892 | 0.246914 | 1254.24 | 2655.0 | clean


</body>
</html>

**Comment by SebChw** [comment]
run one more evaluation this time using some real noise.
