### ISSUE TITLE
Write a step "Train"

### ISSUE THREAD

**Issue by kordc** [SebChw/Actually-Robust-Training#154]
My idea is to have a simple, normal trainer. It can train the model after overfit, but before turning on regularization. Now we can overfit the model, know that it's good, but we don't train it properly, we go straight into regularizing it

**Comment by SebChw** [comment]
What do you mean by train it properly?

**Comment by kordc** [comment]
It's handled by Overfit. The lightning saves all the ckpts, so it's useless
