### ISSUE TITLE
Use the available Quartznet repository and evaluate it on chosen datasets

### ISSUE THREAD

**Issue by kordc** [SebChw/Actually-Robust-Training#16]
- [ ] Evaluate Quartznet15x15 on [ASR dataset](https://huggingface.co/datasets/librispeech_asr). Measure the WER and time required for each prediction. Think/read about a time metric, like inference_time/1s_of_sample.
- [ ] Evaluate Quartznet15x15 using the same method on the Snips-SmartSpeaker dataset, which will be available from HF datasets as soon as #37 is closed
- [ ] Add some white, and real-world noise to both datasets above and measure performance on them once again
- [ ] Create a nice-looking comparison, that everyone can look at. 

Use the Nemo ASR collection from Nvidia. I'll post an example in a comment.
https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/api.html

**Comment by kordc** [comment]
quartznet15x5: WER 0.0447, 2.46it/s

At first it appears being worse than the Conformer, but in further task we can experiment with it

**Comment by SebChw** [comment]
It also seems to be a little bit slower than the small conformer. But Iterations/sec doesn't tell us much. @kordc please do some measurement on how long inference on one second of audio takes.

Also difference of 1% in WER is not that much. For the comparison to be more reliable we should test it also with some noisy data.

**Comment by SebChw** [comment]
Test it on some noisy data, maybe augment data with noise. Measure it's performance. Check memory occupation during inference.

**Comment by kordc** [comment]
@Tymon-Dydowicz look at the updated description

**Comment by kordc** [comment]
example use of the Nemo:
```py
import nemo.collections.asr as nemo_asr
asr_model = nemo_asr.models.EncDecCTCModelBPE.from_pretrained(model_name="stt_en_conformer_ctc_small")
asr_model.transcribe(paths2audio_files=[r"C:\polibuda\audio\data_prepared\en\librispeech\audios\nzDKVo9jMkSQBeqIZ4imPoivp839vI3Tp5fHOVMDrGwSdiLeVMwov0CpJotVNSkbcOedL53JgUAcohPSPSlo23CB6qQrZLJ4srS3BWa0uYp6W7.wav"])
```

or using csv from dataset

```py
librispeech_path = r"C:\polibuda\audio\data_prepared\en\librispeech\\"
df = pd.read_csv(librispeech_path+r"test-clean.csv", sep="\t")
preds = asr_model.transcribe(paths2audio_files=[
    librispeech_path+row["filepath"] for _, row in df.iterrows()])
targets = [row["text"] for _, row in df.iterrows()]
```

About WER metric:
```py
from torchmetrics import WordErrorRate
wer = WordErrorRate()

wer(preds, targets)
```

**Comment by SebChw** [comment]
Allegedly 15x15 is worse than 15x5 and there is no pretrained versions of 15x15 so use 15x5

**Comment by SebChw** [comment]
Try tu use dataset #37 to evaluate
