### ISSUE TITLE
Remove `to` function from project

### ISSUE THREAD

**Issue by SebChw** [SebChw/Actually-Robust-Training#179]
Since every step selects device on the fly this is probably not needed

![image](https://github.com/SebChw/Actually-Robust-Training/assets/66476124/c6b15f4f-ea25-4de4-9a36-03754617e2a9)

![image](https://github.com/SebChw/Actually-Robust-Training/assets/66476124/8d5d74d0-435c-416c-9c01-5f992b83f561)

**Comment by kordc** [comment]
Agree
