### ISSUE TITLE
Do quick research on hiding notebook cells in github

### ISSUE THREAD

**Issue by SebChw** [SebChw/Actually-Robust-Training#181]
Just check if it can be simply done. If yes adjust tutorials. If not just leave as it is

**Comment by kordc** [comment]
It'd be easily done only if we store the file as html or markdown. The jupyter rich rendering on github doesn't support it, we have to wait for them. It's not really possible to override their rendering.

It's huge that we have them rendered on default, but for some reasons the html tag is not properly there

I close this issue, as it can't be done for now
