### ISSUE TITLE
Find and implement model which produces speaker embeddings

### ISSUE THREAD

**Issue by dkoterwa** [SebChw/Actually-Robust-Training#34]
I think that this is the first step in order to build a good speaker recognition model. We have to produce quality embeddings inside Siamese Network, which will output high similarity for utterances from same user, and high dissimilarity for utterances of two different users.

**Comment by dkoterwa** [comment]
https://github.com/pytorch/vision/blob/main/torchvision/models/squeezenet.py

**Comment by dkoterwa** [comment]
Current approach: learning about and testing SqueezeNext CNN to produce embeddings
https://arxiv.org/pdf/1803.10615.pdf

**Comment by SebChw** [comment]
Find existing solution and test it

**Comment by dkoterwa** [comment]
Colab with existing solution: https://colab.research.google.com/drive/1WxR48YDRyyXs9RMfkQxGeSlJF-YFleyX?usp=sharing

**Comment by SebChw** [comment]
Now try to train it on dataset created by Michal Zawieja

**Comment by dkoterwa** [comment]
https://github.com/d-li14/mobilenetv3.pytorch

Found mobilenetv3 code, will try to implement that for our data
