### ISSUE TITLE
Find and prepare data to train Siamese Network.

### ISSUE THREAD

**Issue by dkoterwa** [SebChw/Actually-Robust-Training#35]
1. Find a lot of data
2. Read how to prepare it in optimal way (depends on a loss function we are going to use)
3. Create a script making data for training

edit1: we have to make sure that data has annotations about the user. We must know that because we will produce positive, anchor, and negative samples. Thanks to annotations, we will not make mistakes in making these triples.

**Comment by dkoterwa** [comment]
https://commonvoice.mozilla.org/pl/datasets

**Comment by Nyaa97** [comment]
https://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox2.html
