### ISSUE TITLE
Prepare datasets on HuggingFace

### ISSUE THREAD

**Issue by kordc** [SebChw/Actually-Robust-Training#37]
- [x] convert Fluent Speech Dataset to HF from https://www.kaggle.com/datasets/tommyngx/fluent-speech-corpus 
- [x] Request the Snips datasets
- [x] Convert Snips to HF datasets https://github.com/sonos/spoken-language-understanding-research-datasets

**Comment by kordc** [comment]
@JanekDev  @Wojciechm-AdapptLimited 
podsyłam link do datasetów snips. https://we.tl/t-Ga0Kc2VGI8 
Wystarczy, jak jeden z was to zrobi, a drugi zajmie się Fluent Speech z Kaggle.
Dajcie znać kto co robi. Pamiętajcie, żeby link do wetransferu nie wygasł

**Comment by JanekDev** [comment]
pobrałem snips, mogę się tym zająć

**Comment by JanekDev** [comment]
snips: [link](https://huggingface.co/datasets/MWilinski/snips_slu_v1.0)

**Comment by VVoytus** [comment]
fluent: [link](https://huggingface.co/datasets/IamV/fluent_slu_v1.0)

**Comment by SebChw** [comment]
Good job boys 🔥
