### ISSUE TITLE
Experiment with whisper as a tool for dataset creation

### ISSUE THREAD

**Issue by SebChw** [SebChw/Actually-Robust-Training#39]
Get familiar with [this dataset](https://drive.google.com/file/d/1f6dp72D9WxErXvaZP6KIBLv4-eKpvLZa/view). In each folder it contains utterances of given words. This concrete dataset is synthezied and after inspection the quality is far from perfect. 

I wonder if it is possible to create similar dataset using whipser (or maybe some different speech to text model) that can generate timestamps. The pipeline would be as follows:
* load speech
* run it through whisper using [stable-ts](https://github.com/jianfch/stable-ts)
* Now let's say you obtained such timestamps
![image](https://user-images.githubusercontent.com/66476124/228472724-586458a0-4262-4635-8fd9-ce5bba5aa73c.png)
So you cut audio from 0:0:0 to 0:0:62 and save it to folder named `And` you repeat the process for every word.

Repeat for many speech sources and voila we have our not synthetic dataset.

**Comment by BbqGamer** [comment]
Link to collab with some experimentation
https://colab.research.google.com/drive/1nx0qQwWK5DQi3B0_a-c2quv_zntigEcS?usp=sharing
