### ISSUE TITLE
Create documentation page 

### ISSUE THREAD

**Issue by SebChw** [SebChw/Actually-Robust-Training#46]

**Comment by maciejbilinski** [comment]
https://github.com/readthedocs/sphinx_rtd_theme

https://rtd-sphinx-theme-sample-project.readthedocs.io/en/latest/

**Comment by ErykWalter** [comment]
found an interesting tool if you're not familiar with sphinx: https://github.com/pdoc3/pdoc
if you want to add a page for a project take a look at this: https://github.blog/2016-08-22-publish-your-project-documentation-with-github-pages/
it is also possible to automate generating docs with github action but I haven't found any easy solution yet

**Comment by SebChw** [comment]
I alsow found something for mkDocs https://realpython.com/python-project-documentation-with-mkdocs/. So as far as I understand we have a choice between Sphinx and mkdocs. I think most packages uses Sphinx. However, HF documentation seems to use mkdocs (I like it)

**Comment by SebChw** [comment]
@ErykWalter concerning this automatic tools like pdoc we should probably make type hints for everything before generating this documentation. Shouldn't we ?

**Comment by SebChw** [comment]
Here some comparison between them https://www.reddit.com/r/Python/comments/kidjd9/mkdocs_vs_sphinx_for_static_site_generation/ 
https://github.com/encode/httpx/discussions/1220

We'll stick to Sphinx

**Comment by SebChw** [comment]
However the `rst` format seems to be quite hard to write in so we can try to use Sphing with MyST https://myst-parser.readthedocs.io/en/v0.15.1/sphinx/intro.html

**Comment by SebChw** [comment]
Docs created. Now have to be filled in https://audio-research-toolkit.readthedocs.io/en/latest/
