### ISSUE TITLE
Make art ready for v2 release

### ISSUE THREAD

**Issue by SebChw** [SebChw/Actually-Robust-Training#60]
Before asking big brains to test art we must make sure that it looks professional.

Acceptance criterion
- [x] Updated readme. 
- [x] tags added
- [ ] release created.
- [x] about
- [x] All v.02 issues must be closed
- [x] Change the name from audio research toolkit to actually robust training

**Comment by kordc** [comment]
Tags, and about will be created along with the release. Now we just have to close all v0.2 issues and we'll be ready to go

**Comment by kordc** [comment]
After #174 we're ready to to a release
