### ISSUE TITLE
Improve run_all funtion from Experiment.py

### ISSUE THREAD

**Issue by SebChw** [SebChw/Actually-Robust-Training#62]
2 Things were suggested:
1. Other way of skipping steps - this integer indicator may be very cumbersome in later stages.
~~2. Checking whether the code was changed.~~

Both things should be simple. My suggestion for now is:
1. We iterate over all checks and if all are passed we consider step to be passed.
~~2. As step is being run we save model's code to some hidden folder and calculate it's hash. When step is run the next time. We compare hashes. We show warning to the user that this step should be rerun.~~

If anyone solving this task will have better ideas please suggest them

Acceptance Criteria:
- [x] Checking progress within experiment is no longer done based on integer counter
~~Some primitive method for checking whether code changed and experiment should be done is implemented~~

**Comment by SebChw** [comment]
I think the second checkmark should be another issue.

**Comment by kordc** [comment]
So we can close this one? @SebChw
