### ISSUE TITLE
Verify if we should stick to unclear injections

### ISSUE THREAD

**Issue by SebChw** [SebChw/Actually-Robust-Training#63]
There are few places in code where we inject stuff to other class dynamically e.g `check.name = step.name` in Experiment.py in run_all function. These are nice to use but may be very cumbersome in later period. I already don't know why I did this injection. All these should be verified and should be handled in more clear and concise way.

Acceptance criteria:
- [ ] Identify all places with such injections
- [ ] Refactor them so that it is clear why we do certain injection

**Comment by kordc** [comment]
After #84 and #91 I think there're no other ones. The initial one is also gone.
When #91 is merged I'll close this one, unless @SebChw disagrees
