### ISSUE TITLE
get rid of STEPS_REGISTRY

### ISSUE THREAD

**Issue by SebChw** [SebChw/Actually-Robust-Training#64]
it is introduced in `step.py` and used just by `metric_calculator` in defining exception of when metric shouldn't be calculated. 

The idea beside MetricCalculator is that this is a singleton and user doesn't pass it anywhere. It would require dozen of passes and definitions from the user. 

The only problem is that when we want to define exception (moment when metric shouldn't be calculated) we need list of all STEPS used within this experiment.

My idea is that `Experiment` can pass this to the metric_calculator before we run `run_all` function and then these exceptions are registered.

Acceptance criteria:
- [x] Refactor code so that there is no need of STEPS_REGISTRY and access to steps used within experiments is simpler.

**Comment by kordc** [comment]
Closing this one, as referenced in the PR
