### ISSUE TITLE
Unify models usage

### ISSUE THREAD

**Issue by kordc** [SebChw/Actually-Robust-Training#71]
For now, each model may be required to be initialized many times (see [tutorial(https://github.com/SebChw/art_template/blob/mnist_tutorial_cookiecutter/%7B%7Bcookiecutter.project_slug%7D%7D/exp1/tutorial.ipynb) while overfitting entire dataset).

**Comment by mmaecki** [comment]
Is it about assigning new model to clear weights?

**Comment by kordc** [comment]
@mmaecki Yes, the way we need user to provide his models to a step should be unified
