### ISSUE TITLE
Use previously written Logging utils

### ISSUE THREAD

**Issue by SebChw** [SebChw/Actually-Robust-Training#73]
@mmaecki added additional logging utilities now we should use them in Steps.

1. Use Adapter in tutorial
2. Allow user to set when step should be logged to neptune. Pass it to lightning Trainer in steps
3. Add automatic tags to experiment. When someone uses Evaluatebaslines then neptune experiment should have such tag

**Comment by mmaecki** [comment]
Step 1 is already done.
But it seems like I might need some help with step 2. I don't see the reason why my code doesn't work @SebChw
It crushes when the trainer tries to log something into Neptune, specifying that the path (with expected logs) does not exist.
Keep in mind, that you will need to provide Neptune with your own API key.

**Comment by kordc** [comment]
Is `art\utils\neptun_api_wrapper.py` still used?

**Comment by kordc** [comment]
same question about `art/utils/loggers.py`

**Comment by mmaecki** [comment]
As far as I'm concerned, neither loggers.py nor neptun_api_wparrer.py are used.
However @SebChw should confirm if he didn't use them

**Comment by kordc** [comment]
you should also delete loggers.py

**Comment by kordc** [comment]
anyway I'll do it in another PR. closing
