### ISSUE TITLE
Write tests for tutorials

### ISSUE THREAD

**Issue by kordc** [SebChw/Actually-Robust-Training#78]
Tutorial is a special case of using art, we should have a test that runs all jupyter cells and see whether there's no error.

**Comment by SebChw** [comment]
I'd treat these as integration tests. Maybe each cell should become an integration test? Use `pytest`

**Comment by kordc** [comment]
@SebChw `Maybe each cell should become an integration test?` It's more tricky than that - Each cell may be (and it often is) dependent on the previous cells.

**Comment by mmaecki** [comment]
I found two approaches:
https://chat.openai.com/share/7b83f86f-4675-431e-96aa-c4871031522a - feels more robust
https://semaphoreci.com/blog/test-jupyter-notebooks-with-pytest-and-nbmake - easier and faster, however doesn't quite meet the main objectives of the integration tests

**Comment by alex-remedios** [comment]
Hi @mmaecki (sorry for intruding), I develop nbmake -- do you have any features requests or ideas?

**Comment by mmaecki** [comment]
> Hi @mmaecki (sorry for intruding), I develop nbmake -- do you have any features requests or ideas?

Hi @alex-treebeard. Now that I changed the idea of a test a bit, it seems like nbmake will be very useful to me. However, the option for ignoring expected errors doesn't work for me.
I have changed the source code of  jupyter by adding
```"execution": { 
    "allow_errors": true,
    "timeout": 300
   },``` inside the metadata section, and the test is still interrupted by an exception thrown inside the notebook.
