### ISSUE TITLE
Tutorial check fail

### ISSUE THREAD

**Issue by mmaecki** [SebChw/Actually-Robust-Training#81]
In last cell in the tutorial the regularization step fails.
Is it on purpose? 

- [ ] #82

**Comment by kordc** [comment]
I have `0.8999999761581421 ` - it's not greater than 0.9 as it was supposed to be. I changed it in https://github.com/SebChw/art_template/pull/5 to 0.89. You can leave review comments there

**Comment by SebChw** [comment]
MAKE TUTORIAL 100% reproducible by setting seeds. Consider lightning `seed_everything`
