### ISSUE TITLE
Integrate with metaflow

### ISSUE THREAD

**Issue by SebChw** [SebChw/Actually-Robust-Training#99]
@mmaecki napisz odczucia

I think that integration with metaflow could be yet another step after we have production ready model

**Comment by mmaecki** [comment]
After getting to know metaflow better and testing, I can say that for now, metaflow shouldn't be our point of interest.

The goal for ART is to help create NN from scratch, whereas metaflow focuses on scaling up and out advanced data science projects. It's a great tool, that we can find useful in the unspecified future when ART will be ready to take this new functionality as a next step after all Karpathy's steps.
Shortly: Metaflow should be considered as the next step after ART.
